use std::error::Error;
use std::fmt;
use std::process::Command;
use std::string::FromUtf8Error;

const TOOLCHAIN_FILE: &str = include_str!("../../../rust-toolchain.toml");
const WORKSPACE_MANIFEST: &str = include_str!("../../../Cargo.toml");
const WORKSPACE_LOCKFILE: &str = include_str!("../../../Cargo.lock");

// ANCHOR: ch01_toolchain_report
#[derive(Debug, Eq, PartialEq)]
pub(crate) struct ToolchainReport {
    pinned_rust: String,
    active_rustc: String,
    active_cargo: String,
    edition: String,
    resolver: String,
    lockfile_present: bool,
}

impl ToolchainReport {
    pub(crate) fn collect() -> Result<Self, DoctorError> {
        Ok(Self {
            pinned_rust: quoted_value(TOOLCHAIN_FILE, "channel")?.to_owned(),
            active_rustc: command_version("rustc")?,
            active_cargo: command_version("cargo")?,
            edition: quoted_value(WORKSPACE_MANIFEST, "edition")?.to_owned(),
            resolver: quoted_value(WORKSPACE_MANIFEST, "resolver")?.to_owned(),
            lockfile_present: WORKSPACE_LOCKFILE
                .starts_with("# This file is automatically @generated by Cargo."),
        })
    }

    #[must_use]
    pub(crate) fn is_match(&self) -> bool {
        self.active_rustc == self.pinned_rust
            && self.active_cargo == self.pinned_rust
            && self.lockfile_present
    }
}

impl fmt::Display for ToolchainReport {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        let status = if self.is_match() { "ok" } else { "mismatch" };
        let lockfile = if self.lockfile_present {
            "present"
        } else {
            "missing"
        };
        let pinned_rust = &self.pinned_rust;
        let active_rustc = &self.active_rustc;
        let active_cargo = &self.active_cargo;
        let edition = &self.edition;
        let resolver = &self.resolver;

        writeln!(formatter, "toolchain/status {status}")?;
        writeln!(formatter, "rust/pinned {pinned_rust}")?;
        writeln!(formatter, "rustc/active {active_rustc}")?;
        writeln!(formatter, "cargo/active {active_cargo}")?;
        writeln!(formatter, "edition {edition}")?;
        writeln!(formatter, "resolver {resolver}")?;
        writeln!(formatter, "lockfile {lockfile}")
    }
}
// ANCHOR_END: ch01_toolchain_report

#[derive(Debug)]
pub(crate) enum DoctorError {
    MissingValue(&'static str),
    CommandIo {
        program: &'static str,
        source: std::io::Error,
    },
    CommandFailed(&'static str),
    InvalidUtf8 {
        program: &'static str,
        source: FromUtf8Error,
    },
    InvalidVersionOutput(&'static str),
}

impl fmt::Display for DoctorError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::MissingValue(key) => write!(formatter, "missing source-controlled value: {key}"),
            Self::CommandIo { program, .. } => {
                write!(formatter, "could not run {program} --version")
            }
            Self::CommandFailed(program) => {
                write!(formatter, "{program} --version returned a failure status")
            }
            Self::InvalidUtf8 { program, .. } => {
                write!(formatter, "{program} --version returned non-UTF-8 output")
            }
            Self::InvalidVersionOutput(program) => {
                write!(
                    formatter,
                    "{program} --version returned an unexpected format"
                )
            }
        }
    }
}

impl Error for DoctorError {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        match self {
            Self::CommandIo { source, .. } => Some(source),
            Self::InvalidUtf8 { source, .. } => Some(source),
            Self::MissingValue(_) | Self::CommandFailed(_) | Self::InvalidVersionOutput(_) => None,
        }
    }
}

fn quoted_value<'a>(text: &'a str, key: &'static str) -> Result<&'a str, DoctorError> {
    text.lines()
        .filter_map(|line| line.split('#').next())
        .filter_map(|line| line.split_once('='))
        .find_map(|(candidate, value)| {
            if candidate.trim() == key {
                Some(value.trim().trim_matches('"'))
            } else {
                None
            }
        })
        .filter(|value| !value.is_empty())
        .ok_or(DoctorError::MissingValue(key))
}

fn command_version(program: &'static str) -> Result<String, DoctorError> {
    let output = Command::new(program)
        .arg("--version")
        .output()
        .map_err(|source| DoctorError::CommandIo { program, source })?;

    if !output.status.success() {
        return Err(DoctorError::CommandFailed(program));
    }

    let stdout = String::from_utf8(output.stdout)
        .map_err(|source| DoctorError::InvalidUtf8 { program, source })?;

    stdout
        .split_whitespace()
        .nth(1)
        .map(str::to_owned)
        .ok_or(DoctorError::InvalidVersionOutput(program))
}
